### ISSUE TITLE
[1.17.1] Game crashes when mod is loaded.

### ISSUE THREAD

**Issue by Gbergz** [Mrbysco/Slab-Machines#10]
## Client Info
* Minecraft Version: 1.17.1

* Forge Version: 37.0.43
* Mod Version: 1.1 | https://www.curseforge.com/minecraft/mc-mods/slab-machines/files/3413164
* Java Version: 16

## Issue Description
Booting up the game on newer forge versions crashes the game.

## Reproduce Steps
Install Slab Machines on 1.17.1 Forge - v37.0.43, 
boot game.
crash.

## Additional Information
Crash-report: https://gist.github.com/Gbergz/45db34b44eab8e847cf0d311096cd7a0

**Comment by Mrbysco** [comment]
Will fix the issue soon. Forge redone the tooltype system
