### ISSUE TITLE
[Bug?]: Furnace Slab provide no light when cooking.

### ISSUE THREAD

**Issue by Gbergz** [Mrbysco/Slab-Machines#11]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

39.0.0

### Mod version

1.1.1

### Java version

Java 17

### Issue Description

Furnace Slabs provide no light when cooking stuff like normal furnaces do etc.

Image: (Vanilla to the left, slab furnace to the right.)
![image](https://user-images.githubusercontent.com/26634554/145984108-2e904174-2780-44d4-a6b0-65c32417b425.png)

### Additional Information

Maybe let it provide half the light levels of the vanilla furnace?

**Comment by Mrbysco** [comment]
Will be fixed in a future release
