### ISSUE TITLE
I cannot get the chests to stack on a one block area.  

### ISSUE THREAD

**Issue by Brado1097** [Mrbysco/Slab-Machines#12]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.18.1

### Mod version

1.18.1

### Java version

Java 17 

### Issue Description

I was trying to replace my storage room to make it more effective and the chests wont allow two in a one block area.

**Comment by Mrbysco** [comment]
Not a bug, there just wasn't any multi-part mod for me to hook into so that functionality was removed for now. 
It's stated in the mods description
