### ISSUE TITLE
[Bug]: This module doesn't seem to be compatible with the double slabs module

### ISSUE THREAD

**Issue by 19300000** [Mrbysco/Slab-Machines#15]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

14.23.5.2860

### Minecraft version

1.12.2

### Mod version

1.0.7

### Java version

jre8.0.51

### Issue Description

Trying to place functional blocks other than crafting slab vertically results in crashes, and trying to stack functional blocks other than crafting slab results in crashes
The above problems also occur when only these two modules are enabled

Honestly, I don't know if this bug should be fixed by you or by the author of double slabs, and I'd appreciate it if you could fix

**Comment by 19300000** [comment]
[Uploading crash-2024-05-06_18.47.01-server.txt…]()

**Comment by 19300000** [comment]
[crash-2024-05-06_18.47.01-server.txt](https://github.com/Mrbysco/Slab-Machines/files/15219935/crash-2024-05-06_18.47.01-server.txt)

**Comment by Mrbysco** [comment]
I no longer support 1.12
