### ISSUE TITLE
1.16 wen?

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/Slab-Machines#9]
Hi!

I love your mods. I am a big fan and I hope you can do me favor!

I want to make new skyblock pack but would like slab furnaces! Could you pls make this mod for 1.16.4?

I love your stuff! Pls make a update!

<3 <3 <3

**Comment by Darkosto** [comment]
Oh wait, I found another mod that can do this so don't feel bad if you can't update this one. Ya know, if you don't have the time or you just want a day off from me. Thanks!

**Comment by Mrbysco** [comment]
I've been thinking about updating it but since the original 1.12 version relied on MC Multipart and that was never updated I would have to overhaul the mod. Will still see what I can do as I really want Slab Machines updated myself.

**Comment by Mrbysco** [comment]
Howdy!

I like your packs. Mostly the ones in the sky :)
I was slabbing around when I found out I was able to slab my machines again :) Sadly enough it's for 1.16.5 and not 1.16.4 so you'll be dissapointed :(

Have a link anyway :) https://www.curseforge.com/minecraft/mc-mods/slab-machines/files/3218250
